import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Check, Image as ImageIcon, Package, Target, Zap } from 'lucide-react';
import { Header } from './Header';
import { api, post, waitForJob } from '../lib/api';
import type { CampaignResponse, Creator, HookTemplate, Product, QuotaItem, Script, ScriptHookInput } from '../types/domain';


export default function BrandProfile() {
  const { id = '' } = useParams(); const navigate = useNavigate();
  const [campaign, setCampaign] = useState<CampaignResponse | null>(null); const [creators, setCreators] = useState<Creator[]>([]); const [hookTemplates, setHookTemplates] = useState<HookTemplate[]>([]); const [selectedProduct, setSelectedProduct] = useState<Product | null>(null); const [selectedCreator, setSelectedCreator] = useState<Creator | null>(null); const [scripts, setScripts] = useState<Script[]>([]); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [quota, setQuota] = useState<Record<string, QuotaItem>>({});
  const load = async () => { const [campaignData, creatorData, templateData, quotaData] = await Promise.all([api<CampaignResponse>(`/campaigns/${id}`), api<Creator[]>('/creators'), api<HookTemplate[]>('/hook-templates'), api<{ quota: Record<string, QuotaItem> }>('/quota')]); setCampaign(campaignData); setCreators(creatorData); setHookTemplates(templateData); setQuota(quotaData.quota); };
  // load intentionally refreshes all page resources when the campaign id changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load().catch(caught => setError(caught instanceof Error ? caught.message : 'Unable to load campaign')); }, [id]);
  useEffect(() => { if (!selectedProduct) return setScripts([]); void api<Script[]>(`/campaigns/${id}/scripts?productId=${selectedProduct.id}`).then(setScripts).catch(() => setScripts([])); }, [id, selectedProduct]);
  const runScriptJob = async (hooks: ScriptHookInput[]) => { if (!selectedProduct) return; setBusy(true); setError(''); try { const { job } = await post<{ job: { id: string } }>('/scripts/jobs', { campaignId: id, productId: selectedProduct.id, hooks, character: selectedCreator?.name ?? null, characterImageUrl: selectedCreator?.imageUrl ?? null, idempotencyKey: crypto.randomUUID() }); const result = await waitForJob<{ scripts: Script[] }>(job.id, (_progress, message) => setStatus(message ?? 'Generating scripts')); navigate(`/campaign/${id}/scripts?productId=${selectedProduct.id}&scriptId=${result.scripts[0]?.id ?? ''}`); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Generation failed'); } finally { setBusy(false); } };
  const regenerate = async () => { if (!campaign) return; setBusy(true); try { const { job } = await post<{ job: { id: string } }>('/campaigns/analyze', { website: campaign.website, forceRegenerate: true, idempotencyKey: crypto.randomUUID() }); await waitForJob(job.id, (_progress, message) => setStatus(message ?? 'Reanalyzing')); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Regeneration failed'); } finally { setBusy(false); } };
  if (!campaign?.brandContext) return <div className="min-h-screen bg-[#050505] text-white grid place-items-center">{error || 'Loading campaign…'}</div>;
  const brand = campaign.brandContext;
  return <div className="min-h-screen bg-[#050505] text-white"><Header type="landing" onGoToLanding={() => navigate('/')} />
    <main className="max-w-5xl mx-auto px-6 py-16 space-y-12">
      <header className="text-center"><p className="text-blue-400 font-bold uppercase text-xs tracking-widest">Brand profile</p><h1 className="text-5xl font-bold mt-3">{brand.brandName}</h1><p className="text-zinc-400 mt-3">{brand.productSummary}</p><button disabled={busy || quota.campaign_analysis?.remaining === 0} onClick={regenerate} className="mt-5 px-4 py-2 border border-zinc-700 rounded-lg disabled:opacity-40">Regenerate ({quota.campaign_analysis?.remaining ?? 0} left)</button></header>
      <section className="bg-zinc-950 border border-zinc-800 rounded-3xl p-7"><h2 className="font-bold text-xl flex gap-2"><Target /> Audience</h2><div className="flex flex-wrap gap-2 mt-5">{brand.targetAudience.map(item => <span key={item} className="px-3 py-2 rounded-full bg-blue-500/10 text-blue-300">{item}</span>)}</div></section>
      <section><h2 className="text-2xl font-bold flex gap-2"><Package /> Choose a product</h2><div className="grid md:grid-cols-3 gap-5 mt-6">{campaign.products.map(product => <button key={product.id} onClick={() => setSelectedProduct(product)} className={`text-left rounded-2xl overflow-hidden border ${selectedProduct?.id === product.id ? 'border-blue-500' : 'border-zinc-800'}`}>{product.imageUrls[0] ? <img src={product.imageUrls[0]} alt="" className="aspect-square w-full object-cover" /> : <div className="aspect-square grid place-items-center bg-zinc-900"><Package /></div>}<div className="p-4 flex justify-between"><span className="font-bold">{product.name}</span>{selectedProduct?.id === product.id && <Check />}</div></button>)}</div></section>
      {selectedProduct && <section><h2 className="text-2xl font-bold">Optional spokesperson</h2><div className="grid md:grid-cols-3 gap-4 mt-5"><button onClick={() => setSelectedCreator(null)} className={`rounded-xl border overflow-hidden text-left ${!selectedCreator ? 'border-purple-500' : 'border-zinc-800'}`}><div className="aspect-[4/3] bg-zinc-900 grid place-items-center text-zinc-500"><ImageIcon className="h-10 w-10" /></div><div className="p-5"><div className="font-semibold">No spokesperson</div><span className="block text-sm text-zinc-500 mt-1">Use the product without a presenter</span></div></button>{creators.map(creator => <button key={creator.id} onClick={() => setSelectedCreator(creator)} className={`rounded-xl border overflow-hidden text-left ${selectedCreator?.id === creator.id ? 'border-purple-500' : 'border-zinc-800'}`}>{creator.imageUrl ? <img src={creator.imageUrl} alt={creator.name} className="aspect-[4/3] w-full object-cover" /> : <div className="aspect-[4/3] bg-zinc-900 grid place-items-center text-zinc-500"><ImageIcon className="h-10 w-10" /></div>}<div className="p-5"><div className="font-semibold">{creator.name}</div><span className="block text-sm text-zinc-500 mt-1">{creator.description}</span></div></button>)}</div></section>}
      {selectedProduct && <section><div className="flex justify-between"><h2 className="text-2xl font-bold flex gap-2"><Zap /> Create strategy</h2><span className="text-sm text-zinc-400">{quota.script_generation?.remaining ?? 0} scripts left</span></div>{scripts.length > 0 && <button onClick={() => navigate(`/campaign/${id}/scripts?productId=${selectedProduct.id}`)} className="mt-5 text-purple-400">View {scripts.length} saved script(s)</button>}<div className="grid md:grid-cols-2 gap-4 mt-6">{hookTemplates.map(template => <button key={template.id} disabled={busy} onClick={() => void runScriptJob([{ text: template.text, templateType: template.templateType, sceneDurationSeconds: template.sceneDurationSeconds, scenes: template.scenes }])} className="p-6 rounded-2xl border border-zinc-800 text-left hover:border-zinc-600 disabled:opacity-50"><strong>{template.title}</strong><span className="mt-2 block text-sm text-zinc-500">{template.text}</span></button>)}{hookTemplates.length === 0 && <div className="p-6 rounded-2xl border border-dashed border-zinc-800 text-sm text-zinc-500">No active hook templates are available.</div>}</div></section>}
      {(busy || error) && <div role="status" className={`fixed bottom-5 left-1/2 -translate-x-1/2 px-5 py-3 rounded-xl ${error ? 'bg-red-950 text-red-200' : 'bg-zinc-800'}`}>{error || status || 'Starting…'}</div>}
    </main></div>;
}
